---
ID: "ab811279-d079-41e0-b6dd-1f4f86356d8e"
Parent: "9678b07b-a005-4866-9044-3af320ce5e3a"
Template: "9678b07b-a005-4866-9044-3af320ce5e3a"
Path: /sitecore/templates/Feature/DreamTeam/Banner/Datasources/Banner/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190302T120349Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
